# -*- coding: utf-8 -*-
"""Homework5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AY1F6CTqasfitzz_Hxs6TGXoBXvyrYeS
"""

!pip install spacy
!pip install newsapi-python

!python -m spacy download en_core_web_lg

import spacy
import en_core_web_lg
import pickle
import pandas as pd
from newsapi import NewsApiClient
from collections import Counter
from string import punctuation

nlp = en_core_web_lg.load()
newsapi = NewsApiClient(api_key='279c1df6854547bc9bc0cdb36bf74d52')

articles = []
for i in range(1, 6):
  if(i == 6): break
  data = newsapi.get_everything(q='coronavirus', language='en', from_param='2021-02-28', 
                                to='2021-03-25', sort_by='relevancy', page=i)
  articles.append(data)

filename = 'articlesCOVID.pckl'
pickle.dump(articles, open(filename, 'wb'))

filename = 'articlesCOVID.pckl'
loaded_model = pickle.load(open(filename, 'rb'))

filepath = '/content/articlesCOVID.pckl'
pickle.dump(loaded_model, open(filepath, 'wb'))

data = []

for i, article in enumerate(articles):
  for x in article['articles']:
    title = x['title']
    date = x['publishedAt']
    description = x['description']
    content = x['content']
    data.append({'title':title, 'date':date, 'desc':description, 'content':content})

df = pd.DataFrame(data)
df = df.dropna()
df.head()

def get_keywords_eng(text):
  result = []
  pos_tag = ['VERB', 'NOUN', 'PROPN']
  doc = nlp(text)

  for token in doc:
    if(token.text in nlp.Defaults.stop_words or token.text in punctuation):
      continue
    if(token.pos_ in pos_tag):
      result.append(token.text)

  return result

results = []

for content in df.content.values:
  results.append([('#' + x[0]) for x in Counter(get_keywords_eng(content)).most_common(5)])

df['keywords'] = results

filename = 'articlesCOVIDmodified.pckl'
pickle.dump(articles, open(filename, 'wb'))

filename = 'articlesCOVIDmodified.pckl'
loaded_model = pickle.load(open(filename, 'rb'))

filepath = '/content/articlesCOVIDmodified.pckl'
pickle.dump(loaded_model, open(filepath, 'wb'))

from wordcloud import WordCloud
import matplotlib.pyplot as plt

text = str(results)
wordCloud = WordCloud(max_font_size=50, max_words=100, background_color="white").generate(text)
plt.figure()
plt.imshow(wordcloud, interpolation="bilinear")
plt.axis("off")
plt.show()